Make read_date optional
kapi2289/vulcan-api pull request #117
Opened 2022-09-10 22:50 UTC by Antoni-Czaplicki

2022-09-10 23:06 UTC, heyngra requested changes
I'm pretty sure you need to move the `read_date` under `attachments` (locally it fixes the issue below)
`ValueError: No mandatory attributes allowed after an attribute with a default value or factory.  Attribute in question: Attribute(name='status', default=NOTHING, validator=<instance_of validator for type <class 'int'>>, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({'key': 'Status'}), type=<class 'int'>, converter=<function int_if_not_none at 0x0000022171003A30>, kw_only=False, inherited=False, on_setattr=None)`

2022-09-10 23:19 UTC, Antoni-Czaplicki commented
> I'm pretty sure you need to move the `read_date` under `attachments`
Thx, I forgot about this

2022-09-11 08:59 UTC, heyngra approved these changes

2022-09-11 09:42 UTC, kuba2k2 approved these changes

2022-09-11 11:00 UTC, merged