Add support for message sending.
kapi2289/vulcan-api pull request #40
Opened 2020-10-04 17:30 UTC by Czapla-dev

2020-10-05 07:34 UTC, Czapla-dev commented
Dodano opcje wysyłania wiadomości do kilku nauczycieli.

2020-10-09 16:24 UTC, kapi2289 requested changes

2020-10-09 16:24 UTC, kapi2289 commented on vulcan/_vulcan.py
> -
Please don't remove these new lines.

2020-10-09 16:24 UTC, kapi2289 commented on vulcan/_vulcan.py
> +        sends message to teaches given by id
Remove the newline before documentation, and start the sentence with a capital letter. Add newlines like in other methods.

2020-10-09 16:24 UTC, kapi2289 commented on vulcan/_message.py
> +                api.dict.get_teacher_json(int(teacher))["Nazwisko"]
Repeating 3 times the same code is inefficient. Fetch the teacher object once, and then use the variable.

2020-10-09 16:24 UTC, kapi2289 commented on vulcan/_vulcan.py
> +    def send_message(self, teachers_id, title, content):
I think that `teachers` would be a better parameter name. And it should accept ids, as well as `Teacher` objects (and maybe teacher names too?)

2020-10-09 16:26 UTC, Czapla-dev commented on vulcan/_vulcan.py
> -
I used black to format that file...

2020-10-18 16:38 UTC, kapi2289 approved these changes

2020-10-18 16:38 UTC, merged