Add support for fetching homeworks (hebe)
kapi2289/vulcan-api pull request #47
Opened 2021-01-05 13:31 UTC by Antoni-Czaplicki

2021-01-05 14:28 UTC, kapi2289 requested changes

2021-01-05 14:28 UTC, kapi2289 commented on vulcan/hebe/_hebe_data.py
> +    async def get_homeworks(
There isn't any plural form of "homework". Instead, use just "homework" or "homework list". (In this line it's better to use just "homework")

2021-01-07 11:15 UTC, kuba2k2 commented on vulcan/hebe/data/_lesson.py
> +class LessonGroup(Serializable):
Use the TeamVirtual class (hebe.model.TeamVirtual) instead for consistency with other modules.

2021-01-07 11:26 UTC, kuba2k2 requested changes

2021-01-07 11:26 UTC, kuba2k2 commented on vulcan/hebe/data/_lesson.py
> +class LessonTime(Serializable):
This may be moved to `hebe.model` and renamed to `TimeSlot` for future usage in the API, e.g. in the `dictionary/timeslot` endpoint.

2021-01-07 11:26 UTC, kuba2k2 commented on vulcan/hebe/data/_lesson.py
> +    :var `~vulcan.hebe.data.LessonRoom` ~.room: Classroom, in which is the lesson
Start the sentences lowercase, to remain consistent with other documentation.

2021-01-11 17:45 UTC, kuba2k2 requested changes

2021-01-11 17:45 UTC, kuba2k2 commented on vulcan/hebe/data/_attendance.py
> +        """
Do not place docstrings after any code, they should be at the beginning of the function.

2021-01-11 17:45 UTC, kuba2k2 commented on vulcan/hebe/data/_attendance.py
> +    :var `~vulcan.hebe.model.Teacher` ~.second_teacher: seccond teacher of the lesson
Fix the typo.

2021-01-11 17:45 UTC, kuba2k2 commented on vulcan/hebe/data/_attendance.py
> +    :var str ~.public_resources: attendance public esources
Fix the typo.

2021-01-11 17:45 UTC, kuba2k2 commented on vulcan/hebe/data/_lesson.py
> +    :var `~vulcan.hebe.model.Teacher` ~.second_teacher: seccond teacher of the lesson
Fix the typo.

2021-01-11 17:45 UTC, kuba2k2 commented on vulcan/hebe/data/_lesson.py
> +        :rtype: Union[AsyncIterator[:class:`~vulcan.hebe.data.Lesson`], List[int]]
Again, docstrings are to be placed before the code.

2021-01-11 23:03 UTC, kuba2k2 requested changes

2021-01-11 23:03 UTC, kuba2k2 commented on vulcan/hebe/data/_attendance.py
> +    """A grade.
This is certainly not a grade :) 
Also, please remove the unneeded line breaks at the end of the docstring.

2021-01-12 14:25 UTC, kuba2k2 approved these changes

2021-01-25 18:07 UTC, kapi2289 approved these changes

2021-01-25 18:07 UTC, merged