Add support for fetching changed lessons, migrate get_base_url to async
kapi2289/vulcan-api pull request #77
Opened 2021-03-10 13:52 UTC by Antoni-Czaplicki

2021-03-14 22:01 UTC, kapi2289 approved these changes

2021-03-15 06:51 UTC, kuba2k2 requested changes

2021-03-15 06:51 UTC, kuba2k2 commented on docs/source/full-docs.rst
> +.. autoclass:: vulcan.data.LessonChange
What is a LessonChange?

2021-03-15 06:51 UTC, kuba2k2 commented on vulcan/_data.py
> +    ) -> Union[AsyncIterator[Lesson], List[int]]:
Getting changed lessons should probably return a ChangedLesson, not a Lesson.

2021-03-15 06:51 UTC, kuba2k2 commented on vulcan/data/__init__.py
> +from ._lesson import ChangedLesson, Lesson, LessonRoom
What about LessonChanges?

2021-03-15 07:14 UTC, Antoni-Czaplicki commented on docs/source/full-docs.rst
> +.. autoclass:: vulcan.data.LessonChange
This is a typo

2021-03-15 07:31 UTC, kuba2k2 requested changes

2021-03-15 07:31 UTC, kuba2k2 commented on vulcan/_data.py
> +        :rtype: Union[AsyncIterator[:class:`~vulcan.data.Lesson`], List[int]]
The return type applies here as well.

2021-03-15 07:33 UTC, Antoni-Czaplicki commented on vulcan/_data.py
> +        :rtype: Union[AsyncIterator[:class:`~vulcan.data.Lesson`], List[int]]
Ah, yes - I missed it

2021-03-17 16:40 UTC, kuba2k2 approved these changes

2021-03-17 16:51 UTC, merged